// src/app/layout.tsx
import { Metadata } from "next";
import ReduxProvider from "../../feature/provider/ReduxProvider";
import Navbar from "@/components/nav/Navbar";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/Footer";
// In layout.tsx oder globals.css




interface LayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "A & O",
  description: "Generated by Ghulam & Khalil",

};

export default function RootLayout({ children }: LayoutProps) {

  return (
    <ReduxProvider>
      <html lang="de">
        <body>
          <header>
            <Navbar />
          </header>
          <main>{children}</main>
          <footer className="">
            <Footer />
          </footer>
          <ToastContainer />
        </body>
      </html>
    </ReduxProvider>
  );
}
